baseURL: /

outputs:
  home:
    - HTML
    - JSON
    - RSS
  page:
    - HTML
    - RSS
  search:
    - HTML
    - JSON
  section:
    - HTML

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

taxonomies:
  category: categories
  tag: tags

related:
  includeNewer: false
  indices:
  - name: categories
    weight: 100
  - name: tags
    weight: 100
  threshold: 80
  toLower: false