apiVersion: v1
kind: Namespace
metadata:
  name: pulsar
---
apiVersion: v1
kind: Service
metadata:
  name: "pulsar-broker"
  namespace: pulsar
  labels:
    app.kubernetes.io/name: pulsar
spec:
  ports:
  - name: pulsar
    port: 6650
  type: NodePort
  selector:
    app.kubernetes.io/name: pulsar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar
  namespace: pulsar
  labels:
    app.kubernetes.io/name: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pulsar
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pulsar
    spec:
     containers:
      - name: pulsar
        image: apachepulsar/pulsar:2.9.1
        command: ["bin/pulsar", "standalone"]
        ports:
          - name: "pulsar"
            containerPort: 6650
        resources:
          requests:
            memory: 256Mi
            cpu: 0.1
